Feature/login
shinonome-inc/backend-final-assignment-kenshi pull request #2
Opened 2023-03-18 06:30 UTC by kenshi-backend

2023-03-18 17:16 UTC, h-iwasaki083 reviewed
遅くなりました🙇‍♀️ご確認お願いします！

＊CIの導入をお願いします！Git Hub actionとしてフォーマットやテスト通過を自動で確認してくれるツールです💪
私の方でもテストの通過は確認しましたが、今後のレビューでも統一して用いられるものなので、[こちら](https://shinonome-inc.notion.site/CI-2023-2-5f932bb1097542d3a63afeb72a7870f1)を参考に設定して下さい。

2023-03-19 02:48 UTC, h-iwasaki083 reviewed
深夜にやったので見落としありました…すみません、重ねてご確認お願いします！🙇‍♀️

2023-03-25 11:41 UTC, kenshi-backend commented on accounts/tests.py
> +        )
こちらこそすみません💦
ありがとうございます

2023-03-25 11:50 UTC, kenshi-backend commented on accounts/views.py
> +    template_name = "accounts/profile.html"
僕の方でもAttributeError出ました
確認不足ですみません🙇‍♂️
修正します。

2023-03-26 03:41 UTC, h-iwasaki083 commented on accounts/views.py
> +User = get_user_model
！！
AttributeErrorの原因、ここでUserが取れていないことみたいです。
User = get_user_model
↓↓↓
User = get_user_model()
にかっこを追加して、関数が実行されるようにしてあげれば解決しそうです👀

2023-03-26 03:43 UTC, h-iwasaki083 commented on accounts/views.py
> +    template_name = "accounts/profile.html"
いえいえ！
原因になっていそうなところ（ヘルプを頼んだ友だちが）見つけたので、[こちら](https://github.com/shinonome-inc/backend-final-assignment-kenshi/pull/2#discussion_r1148469997)ご確認いただければ解決できそうかと思います◎

2023-03-28 05:43 UTC, kenshi-backend commented on accounts/views.py
> +User = get_user_model
できました！本当にありがとうございます🙇‍♂️

2023-03-28 10:04 UTC, h-iwasaki083 commented
1次レビューOKです！
[自動テストの案内](https://github.com/shinonome-inc/backend-final-assignment-kenshi/pull/2#issuecomment-1486251997)に従って、flake8で出ているものだけ修正しておいてください！🙇‍♀️

2023-03-28 13:44 UTC, Akinori13 requested changes
良い感じです！コメントしました！

2023-03-28 13:44 UTC, Akinori13 commented on templates/base.html
> +        <a href="{% url 'accounts:logout'%}">ログアウトする</a>
formタグを使いましょう！！

2023-03-28 13:44 UTC, Akinori13 commented on templates/base.html
> +        <a href="{% url 'accounts:user_profile' user.username %}"><button type="button">{{ user.username }}</button></a>
request.user.usernameの方が良いと思います！

2023-03-28 13:44 UTC, Akinori13 commented on templates/accounts/profile.html
> +    <p>ユーザー名：{{user.username}}</p>
該当のユーザーのusernameになっていますか？
例えば、accounts/akinori12/にアクセスしたときにakinori12が表示されるような感じです！

2023-03-28 14:21 UTC, Akinori13 commented on accounts/tests.py
>      def test_success_get(self):
LogoutはPOSTでお願いします！！
テスト名称をtest_success_postに、リクエストをself.client.postにしましょう！

2023-03-29 13:35 UTC, kenshi-backend commented on templates/accounts/profile.html
> +    <p>ユーザー名：{{user.username}}</p>
なっていそうです...！

2023-03-29 22:38 UTC, kenshi-backend commented on accounts/tests.py
>      def test_success_get(self):
わかりました！修正します。

単純な疑問なのですが、なぜlogoutのテストはgetではなくpostなんですか？

2023-04-01 09:10 UTC, Akinori13 commented on templates/base.html
> +        <a href="{% url 'accounts:logout'%}">ログアウトする</a>
こちら修正できていないようです

2023-04-01 09:10 UTC, Akinori13 commented on templates/base.html
> +        <a href="{% url 'accounts:logout'%}">ログアウトする</a>
こちら修正できていないようです

2023-04-01 09:27 UTC, Akinori13 requested changes
良い感じです！修正できていない箇所を修正しつつ、新たに一点追記しましたので修正をお願いします！

2023-04-01 09:27 UTC, Akinori13 commented on templates/base.html
> +        <a href="{% url 'accounts:user_profile' request.user.username %}"><button type="button">{{ user.username }}</button></a>
あくまでここは自分のアカウントのprofileに行くリンクなので以下の方が良いでしょう。
というのもprofile画面では、{{user}}に訪問先のユーザーが格納されてしまうからです。templateでは、ログインユーザーを指す時は、request.userが安全でしょう
```suggestion
        <a href="{% url 'accounts:user_profile' request.user.username %}"><button type="button">{{ request.user.username }}</button></a>
```

2023-04-02 15:27 UTC, kenshi-backend commented on templates/base.html
> +        <a href="{% url 'accounts:logout'%}">ログアウトする</a>
見落としていました…すみません💦

2023-04-03 13:48 UTC, Akinori13 commented
LGTM

2023-04-03 13:48 UTC, merged